# This is a basic workflow to help you get started with Actions

name: Update README

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Update:
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          architecture: x64

      - name: Update README
        run: python update_readme.py

      - name: Commit and push on changes
        run: |-
          git add .
          git diff
          git config --global user.email "readme-bot@1-2.dev"
          git config --global user.name "README Bot"
          git commit -m "Updated README" -a || echo "No changes to commit"
          git push
